version: '3'
services:
  nginx:
    image: lesky7777/nginx-dashboard
    ports:
      - 80:80
    depends_on:
      - wekan
      - grafana
      - pgadmin
  wekan:
    image: wekanteam/wekan
    ports:
      - 8080:8080
    environment:
      - MONGO_URL=mongodb://mongo:27017/wekan
      - ROOT_URL=http://localhost:8080
      - DISABLE_REGISTRATION=true
      - DEFAULT_USER_USERNAME=benutzer
      - DEFAULT_USER_PASSWORD=benutzer
    volumes:
      - wekan_data:/app/uploads
    depends_on:
      - mongo
    command: node initialize.js
  mongo:
    image: mongo:4.4
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana_data:/var/lib/grafana
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
volumes:
  grafana_data:
  wekan_data:
