version: '3'
services:
  nginx:
    image: lesky7777/nginx-dashboard
    ports:
      - 80:80
    depends_on:
      - wekan
      - grafana

  wekan:
    image: wekanteam/wekan
    ports:
      - 8080:8080
    environment:
      - MONGO_URL=mongodb://mongo:27017/wekan
      - ROOT_URL=http://localhost:8080
    volumes:
      - wekan_data:/app/uploads
    depends_on:
      - mongo
    command: sh -c "sleep 10 && echo 'Creating default user...' && \
                    echo '{
                      \"email\": \"admin@example.com\",
                      \"password\": \"admin\",
                      \"username\": \"admin\"
                    }' | node main.js"

  mongo:
    image: mongo:4.4

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
  wekan_data:
